### PR TITLE
Added comment that TWC3 does not work with non-Tesla vehicle.

### PR DESCRIPTION
**Pull request by RTTTC**

### CODE REVIEW

**Comment by RTTTC** [comment]
@VolkerK62 could you please check if German is correct here? :)

**Review by VolkerK62 — CHANGES_REQUESTED** [review]
Better would be
"Funktioniert nur mit Tesla-Fahrzeugen."

**Comment by RTTTC** [comment]
It seems too much masked?

How about something more explicit, more urgent, more like a warning. 

I would like it to clearly  state that it will not work with any other brand of vehicles ( I think it is a big deal)

**Comment by VolkerK62** [comment]
Ah, your intention was not clear to me.
What about:
`Die Wallbox ist durch evcc nicht direkt regelbar. Die Regelung erfolgt über das Fahrzeug. Deshalb ist die Wallbox ausschließlich mit Tesla Fahrzeugen nutzbar. `
`The Wallbox cannot be controlled directly by evcc. Control is via the vehicle. Therefore, the wall box can only be used with Tesla vehicles.`

**Comment by RTTTC** [comment]
https://github.com/evcc-io/evcc/pull/8329

**Pull request closed without merging**
