### PR TITLE
English Translation

### PR DESCRIPTION
**Pull request by duckfullstop**
**Heavy** Work in Progress (and probably will be for a fair while), but I wanted to get this flagged up so others can contribute / share thoughts.

My plan is to translate as much as I can (at least the main pages), and possibly leave some of the deeper, more difficult to understand stuff to community translation - is there a potential for adding this to Weblate, like the main codebase?

There may need to be some tidying of file locations, etcetera after this PR is complete, but my intention is to ship a working translation then work on tidying, possibly as part of a Docusaurus upgrade.

### CODE REVIEW

**Comment by duckfullstop** [comment]
Some thoughts I have:
* The Docusaurus title / tagline can't currently be translated (see https://github.com/facebook/docusaurus/discussions/4480). Should we amend these to something simpler, or stick with "Sonne tanken" as a language-neutral tagline?

**Comment by naltatis** [comment]
@duckfullstop nice one! It's a good first step to get our docs international.

**Review by naltatis — APPROVED** [review]

**Comment by duckfullstop** [comment]
LGTM

**Comment by naltatis** [comment]
Ok, I'll merge when all checks pass. The we can move in smaller steps from there ...

**Pull request merged**
